### ISSUE TITLE
TEMP2_insertion.sh: line 287: 23858 Segmentation fault

### ISSUE THREAD

**Issue by caixu0518** [weng-lab/TEMP2#1]
Hello TEMP2 team,

I read your published paper in NAR, and I found  TEMP2 is an effective tool to detect population-scale TE insertion. However, when i used TEMP2 in my study, i found it generated some error information, like Segmentation fault. detailed log messages are as follows.

ESC[34;1;4mFiltered insertion number: 72330 - 7764 (overlap rmsk) 0 (short insertion) - 1345 (high depth) = 63221ESC[0m
There were 50 or more warnings (use warnings() to see the first 50)
ESC[32mgenerate the overall distribution of transposon mapping reads, first map all reads to transposon Sat Mar 13 02:52:42 CST 2021ESC[0m
ESC[32msam to bed and bedGraph, multiple mappers are divided by their map times Sat Mar 13 03:02:29 CST 2021ESC[0m
[bam_sort_core] merging from 0 files and 25 in-memory blocks...
/data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 23858 **Segmentation fault**      (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
/data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 16451 **Segmentation fault**      (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
/data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 32694 **Segmentation fault**      (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
/data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287:  7767 **Segmentation fault**      (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
/data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 24942 **Segmentation fault**      (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
/data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 27339 **Segmentation fault**      (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
/data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 32596 **Segmentation fault**      (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
/data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287:  2670 **Segmentation fault**      (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
/data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287:  3149 **Segmentation fault**      (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
/data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 29690 **Segmentation fault**      (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
ESC[32mestimate de novo insertion number for each transposon using singleton reads      Sat Mar 13 04:21:46 CST 2021ESC[0m
ESC[32mgenerate distribution figures for singleton supporting reads     Sat Mar 13 04:23:33 CST 2021ESC[0m
null device 
          1 
ESC[32mfilter unreliable singleton insertions, also filter 2p insertions overlapped with similar reference transposon copies    Sat Mar 13 04:39:30 CST 2021ESC[0m

Althogh the error happens, the final "SY18Q0047.insertion.bed" file still generated. I dont know whether the error information will influence the final result. 

I‘m appreciated if you can provide some sollutions and comments.

Many thanks.

Best,
Xu

**Comment by tianxiongbb** [comment]
Thanks for your comment! Samtools segmentation error can be driven by various reasons. It looks like something is wrong when TEMP2 tried to used samtools to extract reads from each transposon. I would suggest checking if ${PREFIX}.transposon.bam is truncated or the name of transposons has any non-alpha characters.
This step is to learn the overall distribution of reads in transposons so that TEMP2 can estimate the true de novo insertion rate. So if you are looking for germline insertions which is supported by multiple reads, the results should be still useful.

**Comment by tianxiongbb** [comment]
> Hello TEMP2 team,
> 
> I read your published paper in NAR, and I found TEMP2 is an effective tool to detect population-scale TE insertion. However, when i used TEMP2 in my study, i found it generated some error information, like Segmentation fault. detailed log messages are as follows.
> 
> ESC[34;1;4mFiltered insertion number: 72330 - 7764 (overlap rmsk) 0 (short insertion) - 1345 (high depth) = 63221ESC[0m
> There were 50 or more warnings (use warnings() to see the first 50)
> ESC[32mgenerate the overall distribution of transposon mapping reads, first map all reads to transposon Sat Mar 13 02:52:42 CST 2021ESC[0m
> ESC[32msam to bed and bedGraph, multiple mappers are divided by their map times Sat Mar 13 03:02:29 CST 2021ESC[0m
> [bam_sort_core] merging from 0 files and 25 in-memory blocks...
> /data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 23858 **Segmentation fault** (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
> /data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 16451 **Segmentation fault** (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
> /data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 32694 **Segmentation fault** (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
> /data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 7767 **Segmentation fault** (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
> /data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 24942 **Segmentation fault** (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
> /data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 27339 **Segmentation fault** (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
> /data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 32596 **Segmentation fault** (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
> /data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 2670 **Segmentation fault** (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
> /data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 3149 **Segmentation fault** (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
> /data/mg1/caix/src/TEMP2-master/bin/TEMP2_insertion.sh: line 287: 29690 **Segmentation fault** (core dumped) samtools view -@ ${CPU} ${PREFIX}.transposon.bam $c1 > ${PREFIX}.transposonMapping/${c1}.sam
> ESC[32mestimate de novo insertion number for each transposon using singleton reads Sat Mar 13 04:21:46 CST 2021ESC[0m
> ESC[32mgenerate distribution figures for singleton supporting reads Sat Mar 13 04:23:33 CST 2021ESC[0m
> null device
> 1
> ESC[32mfilter unreliable singleton insertions, also filter 2p insertions overlapped with similar reference transposon copies Sat Mar 13 04:39:30 CST 2021ESC[0m
> 
> Althogh the error happens, the final "SY18Q0047.insertion.bed" file still generated. I dont know whether the error information will influence the final result.
> 
> I‘m appreciated if you can provide some sollutions and comments.
> 
> Many thanks.
> 
> Best,
> Xu

Thanks for your comment! Samtools segmentation error can be driven by various reasons. It looks like something is wrong when TEMP2 tried to used samtools to extract reads from each transposon. I would suggest checking if ${PREFIX}.transposon.bam is truncated or the name of transposons has any non-alpha characters.
This step is to learn the overall distribution of reads in transposons so that TEMP2 can estimate the true de novo insertion rate. So if you are looking for germline insertions which is supported by multiple reads, the results should be still useful.
