### ISSUE TITLE
The number of SupportReads is not  integer

### ISSUE THREAD

**Issue by Bathroomboss** [weng-lab/TEMP2#13]
Dear Dr. Tianxiong,
TEMP2 is very useful and recently I used it to process my data and got the output file --  _${File}.insertion.bed_, but I noticed something puzzled me. In the eighth column, which represents the support reads, there seems to appear decimals. 

**The pictures below are some examples.**
![image](https://user-images.githubusercontent.com/113091536/231083252-e7ee4f96-c8ec-4469-abdf-c5cb0c40bab0.png)
![image](https://user-images.githubusercontent.com/113091536/231083967-742520e4-7222-4274-a492-08c7d1d37006.png)

I would appreciate it if you could explain the reason behind the appearance of a decimal point in this field.

Best wishes
Liang yu

**Comment by tianxiongbb** [comment]
Hi Liang,

Sometimes a read pair can support multiple transposon insertions due to
homology, e.g. gypsy and gypsy2; or aluY and aluYa. In this case, a read is
counted as 1 / number of supporting TEs for each supported transposon.

Best,
Tianxiong

**Comment by Bathroomboss** [comment]
Thank you!
