### ISSUE TITLE
some samtools command does not use -@ parameter 

### ISSUE THREAD

**Issue by songlyzz** [weng-lab/TEMP2#16]
Hi，
tianxiong 
Recently，I used your software and when I run the test command that I found there is something wrong with samtools below above：
-------------------------------------------------------------------------------------------------------
------ Start pipeline ------
bam file not specified, map raw reads tp genome via bwa mem     Wed Jun 28 15:27:25 CST 2023
transform sam to sorted bam and index it        Wed Jun 28 15:27:27 CST 2023
get concordant-uniq-split reads Wed Jun 28 15:27:30 CST 2023
[M::bam2fq_mainloop] processed 0 reads
check fragment length   Wed Jun 28 15:27:32 CST 2023
insert size set to 95 quantile: 458
get mate seq of the uniq-unpaired       Wed Jun 28 15:27:33 CST 2023
fastq: invalid option -- '@'
Usage: samtools fastq [options...] <in.bam>
Options:
  -0 FILE   write paired reads flagged both or neither READ1 and READ2 to FILE
  -1 FILE   write paired reads flagged READ1 to FILE
  -2 FILE   write paired reads flagged READ2 to FILE
  -f INT    only include reads with all bits set in INT set in FLAG [0]
  -F INT    only include reads with none of the bits set in INT set in FLAG [0]
  -n        don't append /1 and /2 to the read name
  -O        output quality in the OQ tag if present
  -s FILE   write singleton reads to FILE [assume single-end]
  -t        copy RG, BC and QT tags to the FASTQ header line
  -v INT    default quality score if not given in file [1]
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
map paired split uniqMappers and unpaired uniqMappers to transposons    Wed Jun 28 15:27:34 CST 2023
merge fragments in genome and transposon        Wed Jun 28 15:27:34 CST 2023
mytest.t is empty
merge support reads in the same direction within 458 -  Wed Jun 28 15:27:35 CST 2023
expr: syntax error
/TEMP2/bin/TEMP2_insertion.sh: line 208: [: -lt: unary operator expected
sort: cannot read: mytest.supportReads/*.bed: No such file or directory
-------------------------------------------------------------------------------------------------------

It is that samtools fastq and index now did not use the parameter -@ so it can not run，hope you can advise this mistake.

**Comment by songlyzz** [comment]
Meanwhile, If I want to run hg38 genome, I don't find the TE fasta file and TE bed file, and when I use the rmsk file download from (http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/rmsk.txt.gz) ,I find it is different with the rmsk.bed with each column mean. It would be great if you were able to provide reference files in the github.

**Comment by tianxiongbb** [comment]
Hi, only recent version of samtools support multithread (the -@ parameter) in some of its modules. Please re-install your samtools and make sure its version is >=1.9. You can make a conda environment to avoid conflict with your current samtools.
