### ISSUE TITLE
Error on test data

### ISSUE THREAD

**Issue by Partlycloudy029** [weng-lab/TEMP2#17]
**Hi,
When I run the program on test data, unfortunately I have some problems,it shows that message:**

Testing required softwares:
bwa: /public/software/env01/bin/bwa
samtools: /public/software/env01/bin/samtools
bedtools: /public/software/env01/bin/bedtools
------ Start pipeline ------
bam file not specified, map raw reads tp genome via bwa mem     Sat Jul  8 15:07:01 CST 2023
transform sam to sorted bam and index it        Sat Jul  8 15:07:15 CST 2023
get concordant-uniq-split reads Sat Jul  8 15:07:19 CST 2023
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 0 reads
check fragment length   Sat Jul  8 15:07:22 CST 2023
/public/home/soft/TEMP2-master/bin/TEMP2_insertion.sh: line 169: Rscript: command not found
insert size set to 95 quantile:
/public/home/soft/TEMP2-master/bin/TEMP2_insertion.sh: line 172: [: -gt: unary operator expected
get mate seq of the uniq-unpaired       Sat Jul  8 15:07:23 CST 2023
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 0 reads
map paired split uniqMappers and unpaired uniqMappers to transposons    Sat Jul  8 15:07:23 CST 2023
merge fragments in genome and transposon        Sat Jul  8 15:07:24 CST 2023
test.t is empty
merge support reads in the same direction within -      Sat Jul  8 15:07:26 CST 2023
/public/home/zhangtianhao/soft/TEMP2-master/bin/TEMP2_insertion.sh: line 208: [: -: integer expression expected
sort: cannot read: test.supportReads/*.bed: No such file or directory

*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.
Traceback (most recent call last):
  File "/public/home/soft/TEMP2-master/bin/processMergedBed.py", line 108, in <module>
    main()
  File "/public/home/soft/TEMP2-master/bin/processMergedBed.py", line 10, in main
    tel = int(sys.argv[2])
IndexError: list index out of range
merge support reads in different direction within 2 X -         Sat Jul  8 15:07:27 CST 2023
filter candidate insertions which overlap with the same transposon insertion or in high depth region    Sat Jul  8 15:07:27 CST 2023
filter candidate insertions in high depth region        Sat Jul  8 15:07:28 CST 2023
average read number for 200bp bins is 3.2, set read number cutoff to 16
Filtered insertion number: 0 - 0 (overlap rmsk) 0 (short insertion) - 0 (high depth) = 0
/public/home/soft/TEMP2-master/bin/TEMP2_insertion.sh: line 278: Rscript: command not found
generate the overall distribution of transposon mapping reads, first map all reads to transposon        Sat Jul  8 15:07:31 CST 2023
sam to bed and bedGraph, multiple mappers are divided by their map times        Sat Jul  8 15:07:41 CST 2023
estimate de novo insertion number for each transposon using singleton reads     Sat Jul  8 15:08:13 CST 2023
Error: unable to open file or unable to determine types for file test.TPregion.bed

- Please ensure that your file is TAB delimited (e.g., cat -t FILE).
- Also ensure that your file has integer chromosome coordinates in the
  expected columns (e.g., cols 2 and 3 for BED).
Error: unable to open file or unable to determine types for file test.TPregion.bed

- Please ensure that your file is TAB delimited (e.g., cat -t FILE).
- Also ensure that your file has integer chromosome coordinates in the
  expected columns (e.g., cols 2 and 3 for BED).
/usr/bin/env: Rscript: No such file or directory
generate distribution figures for singleton supporting reads    Sat Jul  8 15:08:14 CST 2023
/usr/bin/env: Rscript: No such file or directory
filter unreliable singleton insertions, also filter 2p insertions overlapped with similar reference transposon copies   Sat Jul  8 15:08:14 CST 2023
Error: Invalid record in file test.tmp. Record is
FBgn0000004_17.6        1               0       0       -       0       6       0       0       +       0▒
Error: Invalid record in file test.tmp. Record is
FBgn0000004_17.6        1               0       0       -       0       6       0       0       +       0▒
Calculate frequency of each transposon insertion        Sat Jul  8 15:08:14 CST 2023
get TSD, remove redundant insertions and recalculate de novo insertion rate     Sat Jul  8 15:08:17 CST 2023

*****
***** ERROR: Requested column 2, but database file - only has fields 1 - 0.
Error: unable to open file or unable to determine types for file test.TPregion.bed

- Please ensure that your file is TAB delimited (e.g., cat -t FILE).
- Also ensure that your file has integer chromosome coordinates in the
  expected columns (e.g., cols 2 and 3 for BED).
test.t is empty
calculate de novo insertion rate per genome     Sat Jul  8 15:08:18 CST 2023
clean tmp files Sat Jul  8 15:08:18 CST 2023
Done, Congras!!!🍺🍺🍺

**And the test.insertion.bed file is empty,like this,so how can I solve this problem,thanks.**
![image](https://github.com/weng-lab/TEMP2/assets/119508004/99575f17-0530-4986-9158-381641bc997b)

**Comment by tianxiongbb** [comment]
Hi, this error is because [Rscript](https://www.r-project.org/) is not installed in your environment. I should be more specific in the requirements (will rewrite it).
