### ISSUE TITLE
failed to run test / real TEMP2 pipeline

### ISSUE THREAD

**Issue by maxcoenen** [weng-lab/TEMP2#18]
Hi,
when running the test pipeline, I get the following output:

(base) .@dept3-1:~/TEMP2/test$ /home/t/TEMP2/TEMP2 insertion -l test.1.fastq.gz -r test.2.fastq.gz -I bwa_index/chr2L -g chr2L.fa -R transposon.fa -t rmsk.bed 
-o test_output -c 2
Testing required softwares:
bwa: /usr/bin/bwa
samtools: /usr/bin/samtools
bedtools: /usr/bin/bedtools
------ Start pipeline ------
bam file not specified, map raw reads tp genome via bwa mem     Mon Aug 28 20:26:58 UTC 2023
transform sam to sorted bam and index it        Mon Aug 28 20:27:06 UTC 2023
[bam_sort_core] merging from 0 files and 2 in-memory blocks...
get concordant-uniq-split reads Mon Aug 28 20:27:10 UTC 2023
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 0 reads
check fragment length   Mon Aug 28 20:27:12 UTC 2023
insert size set to 95 quantile: 458
get mate seq of the uniq-unpaired       Mon Aug 28 20:27:13 UTC 2023
[bam_sort_core] merging from 0 files and 2 in-memory blocks...
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 642 reads
map paired split uniqMappers and unpaired uniqMappers to transposons    Mon Aug 28 20:27:14 UTC 2023
merge fragments in genome and transposon        Mon Aug 28 20:27:14 UTC 2023
pass1 - making usageList (1 chroms): 0 millis
pass2 - checking and writing primary data (218 records, 6 fields): 1 millis
merge support reads in the same direction within 458 - 100      Mon Aug 28 20:27:14 UTC 2023
Traceback (most recent call last):
  File "/data/home/t/TEMP2/bin/processMergedBed.py", line 108, in <module>
    main()
  File "/data/home/t/TEMP2/bin/processMergedBed.py", line 19, in main
    transStrand = transRec[0].split(",")[3]
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/home/t/TEMP2/bin/processMergedBed.py", line 108, in <module>
    main()
  File "/data/home/t/TEMP2/bin/processMergedBed.py", line 19, in main
    transStrand = transRec[0].split(",")[3]
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/home/t/TEMP2/bin/processMergedBed.py", line 108, in <module>
    main()
  File "/data/home/t/TEMP2/bin/processMergedBed.py", line 19, in main
    transStrand = transRec[0].split(",")[3]
IndexError: list index out of range

### Followed by: ###

merge support reads in different direction within 2 X 458 - 100 Mon Aug 28 20:27:17 UTC 2023
filter candidate insertions which overlap with the same transposon insertion or in high depth region    Mon Aug 28 20:27:18 UTC 2023
filter candidate insertions in high depth region        Mon Aug 28 20:27:18 UTC 2023
average read number for 200bp bins is 3.15, set read number cutoff to 15.75
Filtered insertion number: 0 - 0 (overlap rmsk) 0 (short insertion) - 0 (high depth) = 0
generate the overall distribution of transposon mapping reads, first map all reads to transposon        Mon Aug 28 20:27:23 UTC 2023
sam to bed and bedGraph, multiple mappers are divided by their map times        Mon Aug 28 20:27:33 UTC 2023
[bam_sort_core] merging from 0 files and 2 in-memory blocks...
estimate de novo insertion number for each transposon using singleton reads     Mon Aug 28 20:27:42 UTC 2023
generate distribution figures for singleton supporting reads    Mon Aug 28 20:27:42 UTC 2023
Error in read.table(Args[8], header = F, row.names = NULL) : 
  no lines available in input
Execution halted
filter unreliable singleton insertions, also filter 2p insertions overlapped with similar reference transposon copies   Mon Aug 28 20:27:43 UTC 2023
Calculate frequency of each transposon insertion        Mon Aug 28 20:27:43 UTC 2023
[bam_sort_core] merging from 0 files and 2 in-memory blocks...
get TSD, remove redundant insertions and recalculate de novo insertion rate     Mon Aug 28 20:27:47 UTC 2023

*****
***** ERROR: Requested column 2, but database file - only has fields 1 - 0.
test.t is empty
calculate de novo insertion rate per genome     Mon Aug 28 20:27:47 UTC 2023
clean tmp files Mon Aug 28 20:27:47 UTC 2023
Done, Congras!!!🍺🍺🍺

**Comment by maxcoenen** [comment]
When I try to run the TEMP2 pipeline with my own data, as such:

``` /home/t/TEMP2/TEMP2 instertion -l /mnt/2ndNAS_folder/KoalaGenomeSurvey/South_Burnett_F_95162_S39P2_L001_R1_001.fastq.gz -r /mnt/2ndNAS_folder/KoalaGenomeSurvey/South_Burnett_F_95162_S39P2_L001_R2_001.fastq.gz -g /home/t/referenceseqs_koala_and_KoRV/GCF_002099425.1_phaCin_unsw_v4.1_genomic_Johnson2018.fna.gz -R /home/t/referenceseqs_koala_and_KoRV/KoRV_ABC_PhER.fa -C 5 -T -c 25 -d -o /home/t/temp2_out -I -t /home/t/repeatmasker/GCF_00209942
5.1_phaCin_unsw_v4.1_genomic_Johnson2018.fna.out.bed6 ```

It does not run, it just returns the help message:

``` TEMP2 -- Version 0.1.6
 -- germline and de novo transposon insertion and deletion analysis

usage:
TEMP2 insertion -h      # for germline and somatic transposon insertion

TEMP2 insertion2 -h     # for only germline transposon insertion

TEMP2 absence -h        # for transposon absence or deletion ```

**Comment by tianxiongbb** [comment]
I just tested the most recent version and it works well. Can you make sure your samtools version >1.9?
The error is because the generation of a intermediate file failed. If you can paste the content of the following file, would be great for debugging: TEMP2/test/test_output/test.supportReads/FBgn0061191_Tc3.-.merged.bed
It should like the following, contains the information of supporting reads for TE Tc3:
chr2L	17130777	17130877	1	FBgn0061191_Tc3,1668,1743,+,0,1	+	17130777	17130877
