### ISSUE TITLE
Consultation Regarding the TEMP2 Insertion Method and Excessive Intermediate File Generation

### ISSUE THREAD

**Issue by zhanxiangzong** [weng-lab/TEMP2#19]
Hi! 
Thank you for providing this valuable tool. I am interested in the TEMP2 insertion method in your project, and I have encountered an issue where it generates an excessive number of intermediate files, numbering in the hundreds of thousands. This quantity of intermediate files exceeds the capacity of my device and impacts its performance. I would like to inquire if there are any settings or configurations that can be adjusted to prevent the generation of excessive intermediate files (without deleting them after completing the task; In other words, the -d parameter doesn't seem suitable for me.). Alternatively, I am interested in learning about any optimization strategies or plans in this regard. I am very thankful for the meaningful tool you have provided.

**Comment by tianxiongbb** [comment]
Hi,
TEMP2 tries to speed up by process multiple transposons in the same time, which will produce files related to transposon numbers by product. It means delete the intermediate/tmp files will affect the performance for now. However, I will suggest avoid make the output folder in a hard drive or similar drive in your machine, which can reduce the issue of I/O that usually crash your system.
