### ISSUE TITLE
Unary operator expected, mergeBed errors when running test data

### ISSUE THREAD

**Issue by heidihyang** [weng-lab/TEMP2#25]
Hi,

I'm having an issue running the test data with the TEMP2 scripts. I've made a conda environment with bio-perl=1.6.924, samtools=1.19.2, bedtools=2.31.1, bwa=0.7.17, and R=4.2.2, and the program is finding the packages through the conda env.

Here is the command I ran:
`../TEMP2 insertion -l test.1.fastq.gz -r test.2.fastq.gz -I bwa_index/chr2L -g chr2L.fa -R transposon.fa -t rmsk.bed -o test_output -c 2`

I'm encountering this error first: `/u/project/vlsork/hyangg/TEMP2/bin/TEMP2_insertion.sh: line 204: [: -lt: unary operator expected`. I then get errors later down the line with mergeBed and others. I've attached the job log: [temp2-joblog.txt](https://github.com/weng-lab/TEMP2/files/14951610/temp2-joblog.txt)

Any help / suggestions would be appreciated!

Best,
Heidi

**Comment by tianxiongbb** [comment]
Hi Heidi,

I apologize for the very late reply. It looks like the reads are not aligned to reference genome properly. I hope this issue is solved and am closing it. Please let me know if you have further questions.
