### ISSUE TITLE
Assembly of the target ERV

### ISSUE THREAD

**Issue by 1577377232** [weng-lab/TEMP2#26]
Hello，Dr. Yu,

I used IGV to check the breakpoints, and extracted the reads mapped within 150bp from TSD, assembled and aligned them.（samtools）

Is there a way to assemble a more complete ERV, via discordant reads and split reads? Because I saw in the BED file,Transposon:Start:End column,The alignment is perfect！**Such as, ERV3： 1：7525：+.**What knowledge can I learn? And what steps can I take to gradually achieve this goal?

Best,
Dan

**Comment by tianxiongbb** [comment]
Hi Dan,

Unfortunately TEMP2 is not designed to assemble the insertion sequences, and I think none of the tools using normal DNA-seq data do. The start and end is inferred simply by where the reads align to the TE, if they are close to the TE start/end, it will output 1:TE_end. However, any internal truncation is undetectable which is limited by read length.

Best,
Tianxiong

**Comment by 1577377232** [comment]
Thank you for your prompt reply！
