### ISSUE TITLE
Program still running while error occurred

### ISSUE THREAD

**Issue by Zhenlisme** [weng-lab/TEMP2#27]
Hi,
I recieved this error message while running **TEMP2 absence** program:

> samtools view: failed to open "Sample1.sort.bam.sorted.bam" for reading: No such file or directory

Is seems that samtools tried to open the file 'Sample1.sort.bam' which can be found in the working directory. But TEMP2 mis referred the file name as 'Sample1.sort.bam.sorted.bam'. The program is still running but I don't know if I should kill the task.

Belows are the script:
```
module load samtools/1.18
module load bwa/0.7.17
module load bedtools/2.30.0
TEMP2 absence -i Sample1.sort.bam -o TEMPab_s1 -r TE.rmsk.bed -t genome.fa.2bit -c 20 -f 500
```

Thank you for your time.
Best

**Comment by tianxiongbb** [comment]
TEMP2 absence only accepts full path of input bam files, so you need to sepcify “-i $pwd/Sample1.sort.bam”

Best,
Tianxiong

**Comment by Zhenlisme** [comment]
Thank you for your quick reply.

I gave `TEMP2 absence` the absolute path. Should I change it to relative path?

**Comment by tianxiongbb** [comment]
Absolute path should work. If not, you might need to rename the bam files from “sort.bam” to “sorted.bam”.

Best,
Tianxiong

**Comment by Zhenlisme** [comment]
Hi again,
I renamed the bam file as sortd.bam and that error disappeared. However, I got new error messages: 

> twoBitToFa: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
> Can't open left.fa since No such file or directory

Do you think if I need to reinstall the package twoBitToFa?

Thank you very much for your time.
Zhen

**Comment by tianxiongbb** [comment]
Yeah, reinstall twoBitToFa from kentutils should work. I hope this issue has been solved, and I am closing this thread.
