### ISSUE TITLE
readlink: illegal option -f

### ISSUE THREAD

**Issue by sbresnahan** [weng-lab/TEMP2#3]
Attempting to run the `TEMP2` script:

`
(TEMP2_TE) Seans-MacBook-Pro:test sbresnahan$ TEMP2
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
/usr/local/bin/TEMP2: line 10: /echo0: No such file or directory
/usr/local/bin/TEMP2: line 11: /echo0: No such file or directory
/usr/local/bin/TEMP2: line 12: /echo0: No such file or directory
/usr/local/bin/TEMP2: line 13: /echo0: No such file or directory
/usr/local/bin/TEMP2: line 14: /echo0: No such file or directory
/usr/local/bin/TEMP2: line 15: /echo0: No such file or directory
`

Attempting to run `TEMP2 insertion`

`
(TEMP2_TE) Seans-MacBook-Pro:test sbresnahan$ TEMP2 insertion -l test.1.fastq.gz -r test.2.fastq.gz -I bwa_index/chr2L -g chr2L.fa -R transposon.fa -t rmsk.bed -o test_output -c 2
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
bash: /TEMP2_insertion.sh: No such file or directory
`

**Comment by tianxiongbb** [comment]
It seems you are executing TEMP2 in Mac OS, which doesn't support "-f" option for "readlink". Currently, we've only tested TEMP2 on the Linux x86_64 system, maybe you can give it a try.
