### ISSUE TITLE
error on test

### ISSUE THREAD

**Issue by piosierra** [weng-lab/TEMP2#7]
Hello,
running the initial test with TEMP2 I get the following 2 errors:

***** ERROR: Requested column 2, but database file - only has fields 1 - 0.
/home/pio/projects/TEMP2/bin/TEMP2_insertion.sh: line 354: intersectBed: command not found
/home/pio/projects/TEMP2/bin/TEMP2_insertion.sh: line 360: bedToBigBed: command not found

Initially it correctly detects bedtools Version:   v2.29.2 
Should those tools be included with that version?

**Comment by tianxiongbb** [comment]
Hi Pio,
Looks like the Bedtools integrated with TEMP2 is conflicted with your version. Re-install bedtools should be able to solve this problem. "bedToBigBed" will be integrated with the later version of TEMP2. but for now you can get it from [kent tools](http://hgdownload.soe.ucsc.edu/admin/exe/).

**Comment by tianxiongbb** [comment]
Hi Pio,
Looks like the Bedtools integrated with TEMP2 is conflicted with your version. Re-install bedtools should be able to solve this problem. "bedToBigBed" will be integrated with the later version of TEMP2. but for now you can get it from [kent tools](http://hgdownload.soe.ucsc.edu/admin/exe/).

**Comment by jdaron** [comment]
Got the same issue, you can a compiled version of bedToBigBed here which is much simpler to get than using kent tools.
wget http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bedToBigBed

**Comment by tianxiongbb** [comment]
The compiled version v2.9 of bedToBigBed has been integrated into TEMP2.
