### ISSUE TITLE
It runs successfully, but always shows some error messages

### ISSUE THREAD

**Issue by iserafiml** [weng-lab/TEMP2#9]
samtools: failed to open "test.transposon.bam" for reading: No such file or directory
[E::hts_open] fail to open file 'test.transposon.bam'

but at the end, it showed : Done, Congras!!!🍺🍺🍺

can I have  a sample test.out file to make sure I am good with the result?

**Comment by tianxiongbb** [comment]
Non-fetal errors wouldn't stop the pipeline from running, but the final output is usually screwed. Below is an output example for file "XXX.insertion.bed". If you didn't get the final results, then I suggest check for the installation of samtools (≥v1.9), bedtools, and bwa.

#Chr	Start	End	Transposon:Start:End:Strand	Frequency	Strand	Type	SupportReads	UnspportReads	5primeSupportReads	3primeSupportReads	TSD	ConfidenceForSomaticInsertion	5splicSiteSupportReads	3spiceSiteSupportReads
chr2L	27	28	FBgn0063503_G6:92:216:-	1	-	singleton	1	0	1	0	unknown	4.71	1	0
chr2L	5484	5868	FBgn0063919_Max-element:8433:8556:+	0.00869565	+	singleton	1	57	0	1	unknown	25.17	0	0
chr2L	76283	76667	FBgn0003519_Stalker:6780:6904:+,FBgn0063897_Stalker4:6887:7011:+	0.00934579	+	singleton	1	53	0	1	unknown	24.98	0	0
chr2L	77351	77735	FBgn0000349_copia:4869:4969:+	0.00854701	+	singleton	1	58	0	1	unknown	70.47	0	0
chr2L	199886	200270	FBgn0063917_McClintock:215:340:+	0.0114943	+	singleton	1	43	1	0	unknown	45.92	0	0
chr2L	205126	205510	FBgn0000481_Doc:534:577:-	0.00787402	-	singleton	1	63	1	0	unknown	28.36	0	0
chr2L	451704	452088	FBgn0000652_F-element:4227:4351:+	0.0120482	+	singleton	1	41	1	0	unknown	11.88	0	0
chr2L	512270	512654	FBgn0000349_copia:4891:5015:+	0.0136986	+	singleton	1	36	0	1	unknown	70.47	0	0
chr2L	532328	532712	FBgn0002745_micropia:5026:5149:+	0.00662252	+	singleton	1	75	0	1	unknown	33.47	0	0
chr2L	561178	561562	FBgn0000481_Doc:269:368:+	0.0126582	+	singleton	1	39	1	0	unknown	28.36	0	0

**Comment by iserafiml** [comment]
Dear Tianxiong, thanks for you replying, I think I got all those software down on my centos 7. I can get some results in my test.soma.summary.txt file but get nothing for test.insertion.bed.

Here is the error showed in the program:
_Traceback (most recent call last):
  File "/root/Document/TEMP2_PROJECT/TEMP2/bin/processMergedBed.py", line 108, in <module>
    main()
  File "/root/Document/TEMP2_PROJECT/TEMP2/bin/processMergedBed.py", line 19, in main
    transStrand = transRec[0].split(",")[3]
IndexError: list index out of range_

and it repeats again and again in the terminal window. Do you have any idea for this problem? Any suggestion or idea would be great for me!

**Comment by tianxiongbb** [comment]
Hi iserafiml, can you check the content in tmpTEMP2/test.supportReads/FBgn0000005_297.+.merged.bed? It should be a tab-delimited file that the 5th column contains the transposon alignment information of supporting reads.

_chr2L	1469447	1469547	1	FBgn0000005_297,49,148,-,0,1	+	1469447	1469547
chr2L	9653203	9653303	1	FBgn0000005_297,6901,6995,+,0,1	-	9653203	9653303_

If things go well, please refer to the final test results [here](https://publications.wenglab.org/TEMP2/data/test.insertion.bed).

**Comment by iserafiml** [comment]
the content in my FBgn0000005_297.+.merged.bed are 

chr2L	1469447	1469547	+	1	FBgn0000005_297,49,148,-,0,1	+	1469447	1469547
chr2L	9653203	9653303	-	1	FBgn0000005_297,6901,6995,+,0,1	-	9653203	9653303

I think the 4th column are different than yours. Any idea?

**Comment by tianxiongbb** [comment]
If the content of tmpTEMP2/test.supportReads/FBgn0000005_297.+.bed is:
_chr2L	1469447	1469547	1	FBgn0000005_297,49,148,-,0	+
chr2L	9653203	9653303	1	FBgn0000005_297,6901,6995,+,0	-_
Then it is mostly likely that "bedtools merge" is doing something different. I think "bedtools merge" by default outputs 3 columns and TEMP2 added additional information to it. In your version "bedtools merge" outputted 4 columns, including strand information in the 4th column, and makes the output file format different.

If this is true, you can update bedtools to a newer version (>v2.0.0 should work but I suggest taking it to the newest version v2.30.0).

**Comment by iserafiml** [comment]
Thanks for your patience, I did it sucessfully.
